# Generated by Django 5.0.12 on 2025-03-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('inspection', 'Inspection'), ('repair', 'Repair'), ('dock_repair', 'Dock Repair')], max_length=50)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=100)),
                ('maintenance_date', models.DateTimeField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bike')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
